---
sidebar: sidebar 
permalink: task-manage-ontap-direct.html 
keywords: direct discovery, direct, system manager, local, local discovery 
summary: 'Si vous avez découvert votre cluster ONTAP sur site directement sans utiliser de connecteur, vous pouvez entrer dans l"environnement de travail pour gérer le cluster à l"aide de System Manager.' 
---
= Gérez des clusters ONTAP sur site découverts directement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous avez découvert votre cluster ONTAP sur site directement sans utiliser de connecteur, vous pouvez ouvrir l'environnement de travail pour gérer le cluster à l'aide de System Manager.

.Conditions requises
L'ordinateur que vous utilisez pour accéder à la console BlueXP doit disposer d'une connexion réseau au cluster ONTAP sur site, de la même manière que vous pouvez fournir des connexions à d'autres ressources de votre réseau privé.

.Limites
Quelques fonctions de System Manager ne sont pas prises en charge par BlueXP.

link:reference-limitations.html["Consultez la liste des limites"].

.Étapes
. Sur la page Canevas, double-cliquez sur le nom d'un environnement de travail ONTAP sur site.
. Indiquez vos identifiants ONTAP.
+
Chaque fois que vous ouvrez l'environnement de travail, vous êtes invité à vous connecter avec vos identifiants ONTAP.

. Utilisez System Manager pour gérer ONTAP.
+
Si vous avez besoin d'aide pour utiliser System Manager avec ONTAP, vous pouvez voir https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^] pour obtenir des instructions détaillées. Voici quelques liens utiles :

+
** https://docs.netapp.com/us-en/ontap/volume-admin-overview-concept.html["Gestion des volumes et des LUN"^]
** https://docs.netapp.com/us-en/ontap/network-manage-overview-concept.html["Gestion du réseau"^]
** https://docs.netapp.com/us-en/ontap/concept_dp_overview.html["Protection des données"^]



